spring:
  datasource:
    url: jdbc:postgresql://ep-falling-wave-ai8pan4a-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_usIZ1fSN2qBJ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:aguilarsolor24@gmail.com}
    password: ${MAIL_PASSWORD:nbftmeavzqlsroev}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_X4BJvA1pT

app:
  frontend:
    url: http://localhost:8100
  admin:
    email: aguilarsolor24@gmail.com

cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID:us-east-1_X4BJvA1pT}
  region: us-east-1