spring:
  datasource:
    url: jdbc:postgresql://ep-falling-wave-ai8pan4a-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_usIZ1fSN2qBJ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true